---
apiVersion: v1
kind: Pod
metadata:
  name: my-php-app
  labels:
    version: v1
spec:
  containers:
  - name: my-php-app
    image: martijnvdd/my-php-app:latest
---
apiVersion: v1
kind: Service
metadata:
  name: my-php-app
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30100
    protocol: TCP
  selector:
    app: my-php-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-php-app
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: my-php-app.local
    http:
      paths:
      - path: /
        backend:
          serviceName: my-php-app
          servicePort: 8080